### ISSUE TITLE
Errors with statistics

### ISSUE THREAD

**Issue by farvadotnet** [ozh/yourls-sqlite#1]
After installing as suggested in the readme I get the following errors on statistics pages (debug mode is on):

> Warning: HY000, 1, no such function: DATE_FORMAT SELECT DATE_FORMAT(`click_time`, '%Y') >AS `year`, DATE_FORMAT(`click_time`, '%m') AS `month`, DATE_FORMAT(`click_time`, '%d') AS >`day`, COUNT(*) AS `count` FROM `yourls_log` WHERE `shorturl` = 'xxxx' GROUP BY `year`, `month`, >`day`; in /home/public/includes/ezSQL/ez_sql_pdo.php on line 165
> 
> Warning: HY000, 1, near "1": syntax error SELECT DATE_FORMAT(`click_time`, '%H %p') AS `time`, >COUNT(*) AS `count` FROM `yourls_log` WHERE `shorturl` = 'xxxx' AND `click_time` > (CURRENT_TIMESTAMP - INTERVAL 1 DAY) GROUP BY `time`; in 
> /home/public/includes/ezSQL/ez_sql_pdo.php on line 165

Replacing DATE_FORMAT calls in yourls-infos.php with similar STRFTIME ones seems to help a little.

**Comment by ozh** [comment]
You'll need to update YOURLS to current master again, I've added a tiny fix to make things cleaner
