### ISSUE TITLE
Just doesn't seem to do anything

### ISSUE THREAD

**Issue by pepa65** [ozh/yourls-sqlite#3]
Fresh install from this repo, version 1.7.1 from the main YOURLS github repo. put the php files in the user directory, refreshed the webpage, and came to the install page. But pressing the button doesn't do anything, and that's that...

**Comment by ozh** [comment]
Just downloaded a fresh 1.7.2 install and this plugin, works just as advertised. Most likely PEBKAC, sorry.

(edit: I say "install this plugin" but I just dropped the two files in /user, of course)

**Comment by pepa65** [comment]
Thanks for your help. It still doesn't work with 1.7.2, but I just realized, it might not work because I'm not using Apache, but Caddy, so it might be a case of PEOS...

**Comment by ozh** [comment]
If you get YOURLS running on Caddy without the SQLite plugin, this plugin should work

**Comment by pepa65** [comment]
When I rename db.php, it runs fine again. When I change it back to db.php, I first get the install page with the 1 button *install YOURLS*. When I click the button, it goes to a totally empty page with url `https://DOMAIN.TLD/admin/install.php?`
